export enum ServiceStatus {
  SCHEDULED = 'SCHEDULED',
  WAITING_SCREENING = 'WAITING FOR SCREENING',
  WAITING_FOR_CONSULTATION = 'WAITING FOR CONSULTATION',
  IN_SCREENING_PROGRESS = 'IN THE SCREENING PROGRESS',
  IN_PROGRESS_CONSULTATION = 'IN PROGRESS OF THE CONSULTATION',
  FINISHED = 'FINISHED',
  CANCELED = 'CANCELED',
  ABSENT = 'ABSENT',
}
