export enum ServiceStatus {
	STARTED_SERVICE = "STARTED SERVICE",
	SERVICE_IN_PROGRESS = "SERVICE IN PROGRESS",
	SERVICE_COMPLETED = "SERVICE COMPLETED",
	TREATMENT_STARTED = "TREATMENT_STARTED",
}