### POST CREATE CLINIC
POST http://localhost:3000/clinic
Content-Type: application/json

{
  "id": null,
  "password": "12345678",
  "name": "Clinica de Exames 7",
  "email": "clinica7@clinica.com.br" ,
  "address": {
    "street": "Rua dos exames 7",
    "number": "123",
    "neighborhood": "Santana",
    "city": "São Paulo",
    "state": "SP",
    "zipCode": "12345-678",
    "country": "Brasil",
    "complement": "Sala 2"
  },
  "contactInfo": {
    "phone": "11 1234-5678",
    "emergencyPhone": "11 98765-4321",
    "emergencyPhone2": "11 98765-4321",
    "emergencyPhone3": "11 98765-4321",
    "email": "contato@clinica1.com.br",
    "extension": "123",
    "extension2": "123",
    "extension3": "123"
  }
}

###

### GET CLINIC
GET http://localhost:3000/clinic/42f014c8-4b60-42d9-bb82-29663aef8a51


### POST CREATE DOCTOR
POST http://localhost:3000/doctor
content-type: application/json

{
  "id": null,
  "password": "123456",
  "name": "Dr. Examinador 3",
  "email": "examinador2@gmail.com",
  "registrationNumber": "123456",
  "specialization": "Neurologista",
  "address": {
    "street": "Rua São Shibituba",
    "number": "123",
    "neighborhood": "jaçana",
    "city": "São Paulo",
    "state": "SP",
    "zipCode": "12345-678",
    "country": "Brasil",
    "complement": "Sala 1"
  },
  "contactInfo": {
    "phone": "11 1234-5678",
    "emergencyPhone": "11 98765-4321",
    "emergencyPhone2": "11 98765-4321",
    "emergencyPhone3": "11 98765-4321",
    "email": "contato@clinica2.com.br",
    "extension": "123",
    "extension2": "123",
    "extension3": "123"
  }
}

### GET DOCTOR
GET http://localhost:3000/doctor/


### POST CREATE PATIENT
POST http://localhost:3000/patients
content-type: application/json

{
  "id": null,
  "name": "Neide",
  "lastName": "Vasco",
  "email": "ire2@gmail.com",
  "password": "123456",
  "dateOfBirth": "1990-01-01",
  "sex": "Female",
  "maritalStatus": "Solteiro(a)",
  "documentation": {
    "cpf": {
      "cpf": "123.456.789-00"
    },
    "rg": {
      "rg": "12.345.678-9"
    },
    "cnh": {
      "cnh": "12345678900"
    },
    "cns": {
      "cns": "12345678900"
    }
  },
  "socioeconomicInformation": {
    "profession": "Professora",
    "educationLevel": "Ensino Superior",
    "housingConditions": "Casa",
    "incomeLevel": "renda mensal domiciliar entre  dois salários e três salários",
    "socialSupport": "Familia"
  },
  "address": {
    "street": "Rua São Shibituba",
    "number": "123",
    "neighborhood": "jaçana",
    "city": "São Paulo",
    "state": "SP",
    "zipCode": "12345-678",
    "country": "Brasil",
    "complement": "Sala 1"
  },
  "contactInfo": {
    "phone": "11 1234-5678",
    "emergencyPhone": "11 98765-4321",
    "emergencyPhone2": "11 98765-4321",
    "emergencyPhone3": "11 98765-4321",
    "email": "contato@clinica2.com.br",
    "extension": "123",
    "extension2": "123",
    "extension3": "123"
  },
  "healthInsurance": "Unimed"
}